import {Selector} from "testcafe";

export const selectors = {
    heroBannerTitle: Selector('h2.tuvp-hero__subheading.ng-scope'),
    heroBannerSubTitle: Selector('h1.tuvp-hero__heading.ng-scope'),
    certifiedVehicleCheckbox: Selector('label').withText('Certified Vehicles'),
    certifiedVehicleToolTipIcon: Selector('span.tuvp-comp-tooltip__icon'),
    certifiedVehicleToolTipContent: Selector('div.tuvp-comp-tooltip__content'),
    hybridCheckbox: Selector('checkbox[label="Hybrid Only"]'),
    modelDropDown: Selector('dropdown[label="Toyota Model"] .tuvp-comp-dropdown__select-text.ng-binding'),
    modelDropDownList: Selector('dropdown[label="Toyota Model"] ul li'),
    priceDropDown: Selector('dropdown[label="Max Price"] .tuvp-comp-dropdown__select-text.ng-binding'),
    priceDropDownList: Selector('dropdown[label="Max Price"] ul li'),
    locationInputBox: Selector('.tuvp-comp-location__input input'),
    locationInputListItems: Selector('.tuvp-comp-location__input-items li'),
    searchToyotaVehiclesButton: Selector('button[ng-click="herosearch.search()"]'),
    searchAllVehicleMake: Selector('a').withText('Search All Vehicle Makes'),
    valueMyCarHeadingText: Selector('.tuvp-hero__ctas p'),
    valueMyCarLink: Selector('a').withText('VALUE MY CAR'),
    searchResultsHeader: Selector('h4[class^="header"]'),
    searchResultsCarTitles: Selector('.item-header.hidden-xs.clickable'),
    priceValuesSearchResultsPage: Selector('div.side-content.hidden-xs h3.price-value'),
    locationNamesSearchResultsPage: Selector('.seller-location span.block.nowrap'),
    locationSideBarFilter: Selector('#location-input'),
    searchResultsSideBarHybridFilter: Selector('#hybrid-button'),
    searchResultsSideBarCertifiedFilter: Selector('#certified-vehicles'),
    searchResultsSideBarMakeFilter: Selector('#make-select'),
    searchResultsSideBarMakeFilterOptions: Selector('#make-select option'),
};
